name: "Build, Push and Release a Docker container to Heroku."
author: "Kamil Klyta"
description: "Build, Push and Release a Docker container to Heroku."
inputs:
  heroku_app_name:
    description: "Name of the heroku application to which the build is to be sent."
    required: true
  heroku_api_key:
    description: "Heroku API key"
    required: true
  dockerfile_directory:
    description: "Dockerfile directory."
    required: true
    default: "./"
  dockerfile_name:
    description: "Dockerfile name. [default=Dockerfile]"
    required: false
    default: "Dockerfile"
  docker_options:
    description: "Additional options of docker build command"
    required: false
    default: ""
  process_type:
    description: "Select process type for wich you want docker container to be uploaded. [default=web]"
    required: false
    default: "web"
branding:
  icon: server
  color: purple
runs:
  using: "node12"
  main: "dist/index.js"
